version: '3.5'

services:
  localstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localstack
    hostname: localstack
    ports:
      - '4566:4566'
    environment:
      # Declare which aws services will be used in localstack
      - SERVICES=iam,s3,lambda
      - DEBUG=1
      # These variables are needed for localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
    networks:
      - server_localstack

networks:
  server_localstack:
    external: true