const OUTPUT_BUCKET = process.env.OUTPUT_BUCKET;
const AUTH0_CLIENT_AUDIENCE = process.env.AUTH0_CLIENT_AUDIENCE;
const AUTH0_CLIENT_ID = process.env.AUTH0_CLIENT_ID;
const AUTH0_CLIENT_SECRET = process.env.AUTH0_CLIENT_SECRET;
const EXTENSION = '.gif';
const MIME_TYPE = 'image/gif';
const THUMB_WIDTH = 300;

module.exports = {
  OUTPUT_BUCKET,
  AUTH0_CLIENT: {
    AUDIENCE: AUTH0_CLIENT_AUDIENCE,
    CLIENT_ID: AUTH0_CLIENT_ID,
    CLIENT_SECRET: AUTH0_CLIENT_SECRET,
  },
  EXTENSION,
  MIME_TYPE,
  THUMB_WIDTH,
};
